name: Python application

on: [push, pull_request]

jobs:
  lint_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip virtualenv wheel setuptools
      - name: Lint with pycodestyle
        run: |
          python3 -m pip install flake8
          python3 -m flake8 . --count --ignore=E125,E126,E127,E128,E402,E741,E731,W503,F401,W504 --show-source --statistics --max-line-length=80 --exclude=__pycache__,.tox,.git/,doc/

  windows_test:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [ '3.6', '3.7' ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: |
          python -m pip install --upgrade pip virtualenv wheel setuptools pytest
          python -m pip install -e .
      - name: Test with pytest
        run: |
          python -m pytest thorcam/tests

  windows_wheels:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [ '3.6', '3.7' ]
        arch: ['x64', 'x86']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}
    - name: Get dependencies
      env:
        ZIP_PASS: ${{ secrets.ZIP_PASS }}
      run: |
        Invoke-WebRequest "https://www.thorlabs.com/software/THO/ThorCam/Programming/Scientific_Camera_Interfaces_07-11-2019.zip" -OutFile "Scientific_Camera_Interfaces_07-11-2019.zip"
        7z x "Scientific_Camera_Interfaces_07-11-2019.zip"
    - name: Make wheel
      run: |
        if (${{ matrix.arch }} -eq "x64") {
          $env:THORCAM_WHEEL_DEPS = ".\Scientific Camera Interfaces\SDK\DotNet Toolkit\dlls\Managed_64_lib"
        } else {
          $env:THORCAM_WHEEL_DEPS = ".\Scientific Camera Interfaces\SDK\DotNet Toolkit\dlls\Managed_32_lib"
        }
        echo "THORCAM_WHEEL_DEPS=$env:THORCAM_WHEEL_DEPS"

        python -m pip install --upgrade pip virtualenv wheel setuptools
        python -m pip install -e .

        python setup.py bdist_wheel
    - name: Upload wheel
      uses: actions/upload-artifact@master
      with:
        name: py_wheel
        path: dist

  docs:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install
      run: |
        python -m pip install --upgrade pip virtualenv wheel setuptools sphinx
        python -m pip install -e .
    - name: Generate docs
      if: github.ref == 'refs/heads/master' && matrix.python == '3.7'
      run: |
        cd doc
        ./make.bat html
    - name: gh-pages upload
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir "C:\docs_temp"
        Copy-Item "doc\build\html\*" "C:\docs_temp" -recurse

        git config --global user.email "moiein2000@gmail.com"
        git config --global user.name "Matthew Einhorn"
        git remote rm origin
        git remote add origin "https://x-access-token:$env:GITHUB_TOKEN@github.com/matham/thorcam.git"

        git checkout --orphan gh-pages
        git rm -rf .
        Remove-Item -recurse * -exclude .git
        Copy-Item "C:\docs_temp\*" .  -recurse
        echo "" > .nojekyll

        git add .
        git commit -a -m "Docs for git-$env:GITHUB_SHA"
        git push origin gh-pages -f
